import type { LedgerType } from '@budjo/shared';

/**
 * What an admin may correct from the History screen.
 *
 * The ledger is append-only, so an "edit" is always a void of the original plus
 * a fresh replacement entry. That works cleanly for entries that stand alone,
 * and not at all for entries that are one half of something:
 *
 *   - transfer_in / transfer_out are two legs of one movement. Rewriting one
 *     leg would leave the two accounts disagreeing about the same transfer.
 *   - advance / advance_repayment are bound to a row in `advances` that the
 *     monthly job reads. Rewriting the entry would not touch the schedule.
 *   - allocation is generated by that job, and is corrected by changing the
 *     allocation amount, which posts its own adjustment.
 *
 * Those are reversed by their own mechanisms, not by hand-editing history.
 */
export const EDITABLE_TYPES: readonly LedgerType[] = ['spend', 'refund', 'adjustment'];
export const VOIDABLE_TYPES: readonly LedgerType[] = ['spend', 'refund', 'adjustment', 'allocation'];

export function canEditType(type: LedgerType): boolean {
  return EDITABLE_TYPES.includes(type);
}

export function canVoidType(type: LedgerType): boolean {
  return VOIDABLE_TYPES.includes(type);
}

export function whyNotEditable(type: LedgerType): string {
  switch (type) {
    case 'transfer_in':
    case 'transfer_out':
      return 'A transfer has two sides. Reverse it with a transfer the other way.';
    case 'advance':
    case 'advance_repayment':
      return 'Advances are settled by the monthly job, not edited by hand.';
    case 'allocation':
      return 'Change the monthly amount under Accounts instead — that posts its own correction.';
    case 'void':
      return 'This entry is already a correction.';
    default:
      return 'This entry cannot be edited.';
  }
}

/**
 * A spend must stay a spend. Keeping the sign tied to the type stops a typo
 * turning a $60 dinner into a $60 credit.
 */
export function isValidAmountForType(type: LedgerType, amountCents: number): boolean {
  if (!Number.isInteger(amountCents) || amountCents === 0) return false;
  switch (type) {
    case 'spend':
      return amountCents < 0;
    case 'refund':
      return amountCents > 0;
    case 'adjustment':
      return true;
    default:
      return false;
  }
}
